import type { ToolManifest, ToolCategory } from '../types/tool';

export const tools: ToolManifest[] = [
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, sentences, and reading time',
    category: 'text',
    tags: ['word', 'count', 'characters', 'text', 'reading time'],
    icon: '📝',
    load: () => import('../tools/text/word-counter'),
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text between camelCase, snake_case, UPPER, lower, and more',
    category: 'text',
    tags: ['case', 'camel', 'snake', 'upper', 'lower', 'text', 'convert'],
    icon: '🔤',
    load: () => import('../tools/text/case-converter'),
  },
  {
    id: 'text-diff',
    name: 'Text Diff',
    description: 'Compare two texts and highlight the differences',
    category: 'text',
    tags: ['diff', 'compare', 'text', 'difference', 'patch'],
    icon: '🔀',
    load: () => import('../tools/text/text-diff'),
  },
  {
    id: 'base64',
    name: 'Base64',
    description: 'Encode and decode Base64 strings',
    category: 'encoders',
    tags: ['base64', 'encode', 'decode', 'binary'],
    icon: '🔐',
    load: () => import('../tools/encoders/base64'),
  },
  {
    id: 'url-encode',
    name: 'URL Encode / Decode',
    description: 'Encode and decode URL components and query strings',
    category: 'encoders',
    tags: ['url', 'encode', 'decode', 'percent', 'query', 'uri'],
    icon: '🔗',
    load: () => import('../tools/encoders/url-encode'),
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Token headers and payloads',
    category: 'encoders',
    tags: ['jwt', 'token', 'decode', 'auth', 'json web token', 'bearer'],
    icon: '🪪',
    load: () => import('../tools/encoders/jwt-decoder'),
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, validate, and minify JSON data',
    category: 'formatters',
    tags: ['json', 'format', 'pretty', 'minify', 'validate', 'lint'],
    icon: '📋',
    load: () => import('../tools/formatters/json-formatter'),
  },
  {
    id: 'markdown-preview',
    name: 'Markdown Preview',
    description: 'Write Markdown and see a live rendered preview',
    category: 'formatters',
    tags: ['markdown', 'preview', 'render', 'html', 'md'],
    icon: '📄',
    load: () => import('../tools/formatters/markdown-preview'),
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate one or many UUIDs (v4) instantly',
    category: 'generators',
    tags: ['uuid', 'guid', 'generate', 'unique', 'id', 'random'],
    icon: '🎲',
    load: () => import('../tools/generators/uuid-generator'),
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum',
    description: 'Generate placeholder Latin text by words, sentences, or paragraphs',
    category: 'generators',
    tags: ['lorem', 'ipsum', 'placeholder', 'text', 'dummy', 'copy'],
    icon: '📜',
    load: () => import('../tools/generators/lorem-ipsum'),
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong, random passwords with custom rules',
    category: 'generators',
    tags: ['password', 'generate', 'random', 'secure', 'strong'],
    icon: '🔑',
    load: () => import('../tools/generators/password-generator'),
  },
];

export const CATEGORIES: ToolCategory[] = ['text', 'encoders', 'formatters', 'generators'];
