import type { ToolManifest, ToolCategory } from '../types/tool';

export const tools: ToolManifest[] = [
  // Text
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, sentences, and reading time',
    category: 'text',
    tags: ['word', 'count', 'characters', 'text', 'reading time'],
    icon: '📝',
    load: () => import('../tools/text/word-counter'),
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text between camelCase, snake_case, UPPER, lower, and more',
    category: 'text',
    tags: ['case', 'camel', 'snake', 'upper', 'lower', 'text', 'convert'],
    icon: '🔤',
    load: () => import('../tools/text/case-converter'),
  },
  {
    id: 'text-diff',
    name: 'Text Diff',
    description: 'Compare two texts and highlight the differences',
    category: 'text',
    tags: ['diff', 'compare', 'text', 'difference', 'patch'],
    icon: '🔀',
    load: () => import('../tools/text/text-diff'),
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test regular expressions with live match highlighting and group capture',
    category: 'text',
    tags: ['regex', 'regexp', 'regular expression', 'match', 'pattern', 'test'],
    icon: '🔍',
    load: () => import('../tools/text/regex-tester'),
  },
  // Encoders
  {
    id: 'base64',
    name: 'Base64',
    description: 'Encode and decode Base64 strings',
    category: 'encoders',
    tags: ['base64', 'encode', 'decode', 'binary'],
    icon: '🔐',
    load: () => import('../tools/encoders/base64'),
  },
  {
    id: 'url-encode',
    name: 'URL Encode / Decode',
    description: 'Encode and decode URL components and query strings',
    category: 'encoders',
    tags: ['url', 'encode', 'decode', 'percent', 'query', 'uri'],
    icon: '🔗',
    load: () => import('../tools/encoders/url-encode'),
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Token headers and payloads',
    category: 'encoders',
    tags: ['jwt', 'token', 'decode', 'auth', 'json web token', 'bearer'],
    icon: '🪪',
    load: () => import('../tools/encoders/jwt-decoder'),
  },
  {
    id: 'html-entities',
    name: 'HTML Entities',
    description: 'Encode and decode HTML entities to prevent XSS and display special characters',
    category: 'encoders',
    tags: ['html', 'entity', 'encode', 'decode', 'escape', 'xss', 'special characters'],
    icon: '🏷️',
    load: () => import('../tools/encoders/html-entities'),
  },
  // Formatters
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, validate, and minify JSON data',
    category: 'formatters',
    tags: ['json', 'format', 'pretty', 'minify', 'validate', 'lint'],
    icon: '📋',
    load: () => import('../tools/formatters/json-formatter'),
  },
  {
    id: 'markdown-preview',
    name: 'Markdown Preview',
    description: 'Write Markdown and see a live rendered preview',
    category: 'formatters',
    tags: ['markdown', 'preview', 'render', 'html', 'md'],
    icon: '📄',
    load: () => import('../tools/formatters/markdown-preview'),
  },
  // Generators
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate one or many UUIDs (v4) instantly',
    category: 'generators',
    tags: ['uuid', 'guid', 'generate', 'unique', 'id', 'random'],
    icon: '🎲',
    load: () => import('../tools/generators/uuid-generator'),
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum',
    description: 'Generate placeholder Latin text by words, sentences, or paragraphs',
    category: 'generators',
    tags: ['lorem', 'ipsum', 'placeholder', 'text', 'dummy', 'copy'],
    icon: '📜',
    load: () => import('../tools/generators/lorem-ipsum'),
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong, random passwords with custom rules',
    category: 'generators',
    tags: ['password', 'generate', 'random', 'secure', 'strong'],
    icon: '🔑',
    load: () => import('../tools/generators/password-generator'),
  },
  {
    id: 'pomodoro',
    name: 'Pomodoro Timer',
    description: 'Focus timer with adjustable work and break intervals and browser notifications',
    category: 'generators',
    tags: ['pomodoro', 'timer', 'focus', 'productivity', 'break', 'countdown', 'work'],
    icon: '🍅',
    load: () => import('../tools/generators/pomodoro-timer'),
  },
  // Converters
  {
    id: 'color-converter',
    name: 'Color Converter',
    description: 'Convert colors between HEX, RGB, and HSL with a live preview',
    category: 'converters',
    tags: ['color', 'hex', 'rgb', 'hsl', 'convert', 'picker', 'css'],
    icon: '🎨',
    load: () => import('../tools/converters/color-converter'),
  },
  {
    id: 'timestamp',
    name: 'Timestamp Converter',
    description: 'Convert Unix timestamps to human-readable dates and back',
    category: 'converters',
    tags: ['timestamp', 'unix', 'epoch', 'date', 'time', 'convert', 'utc'],
    icon: '⏱️',
    load: () => import('../tools/converters/timestamp'),
  },
  {
    id: 'csv-to-json',
    name: 'CSV → JSON',
    description: 'Convert CSV data to JSON — supports headers, custom delimiters',
    category: 'converters',
    tags: ['csv', 'json', 'convert', 'table', 'data', 'spreadsheet'],
    icon: '📊',
    load: () => import('../tools/converters/csv-to-json'),
  },
  {
    id: 'number-base',
    name: 'Number Base Converter',
    description: 'Convert numbers between decimal, binary, octal, and hexadecimal',
    category: 'converters',
    tags: ['binary', 'hex', 'decimal', 'octal', 'base', 'convert', 'number'],
    icon: '🔢',
    load: () => import('../tools/converters/number-base'),
  },
];

export const CATEGORIES: ToolCategory[] = ['text', 'encoders', 'formatters', 'generators', 'converters'];
